name: deploy

env:
  BASE_URL: /monorepo-template
  BUILD_PACKAGE_NAME: "web"
  PUBLISH_DIR: ./packages/web/dist

# 手动触发，不需要自动部署
# 自动部署的时机是在publish之后
on: workflow_dispatch

jobs:
  npm:
    steps: # 任务的步骤
      - name: checkout code repository # 步骤的名字 切到对应的分支
        uses: actions/checkout@v2 # 使用actions/checkout@v2这个action
        with: # 这个action的参数
          fetch-depth: 0

      - name: Deploy to GitHub Pages
        uses: ./.github/actions/deploy-docs
        with:
          build: BASE_URL=$BASE_URL pnpm -r build --filter=$BUILD_PACKAGE_NAME
          publish_dir: $PUBLISH_DIR
          github_token: ${{ secrets.GITHUB_TOKEN }}
